name: .NET core Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
     - name: checkout-bitbucket
       run: git clone https://waizguy@bitbucket.org/jwpolaris/piranha.core.git
      steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity norma
      
     - name: Polaris Scan
        uses: synopsys-sig/synopsys-action@v1.11.0
        env:
          DETECT_DETECTOR_SEARCH_DEPTH: 10
        with:
          ### SCANNING: Required fields
          polaris_server_url: ${{ vars.POLARIS_SERVERURL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_assessment_types: "SCA"
          
          
          ### SCANNING: Optional fields
          polaris_application_name: AJW-${{ github.event.repository.name }}
          # polaris_project_name: ${{ github.event.repository.name }}
          
          ### PULL REQUEST COMMENTS: Uncomment below to enable
          polaris_prComment_enabled: true 
          github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled

          ### SARIF report parameters
          polaris_reports_sarif_create: true
          polaris_upload_sarif_report: true
    l
